.\" Man Page for Pig.c, a program in homework 3 for CSCI 241
.\" Zac Plett and Ezra Goss - Fall 2017

.TH pig_man 1 "03 October 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B pig_man
\- a man page for pig.c

.SH DESCRIPTION
Pig takes in words in English and translates them to Pig Latin!

.SH OPTIONS
.IP "-h or -?"
Brings up a help message for how use the program!

.SH AUTHORS
Zac Plett and Ezra Goss (Fall 2017)

.SH BUGS
None!
