.\" Man Page for Unpig.c, a program in homework 3 for CSCI 241
.\" Zac Plett and Ezra Goss - Fall 2017

.TH unpig_man 1 "03 October 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B unpig_man
\- a man page for unpig.c

.SH DESCRIPTION
Unpig takes in words in Pig Latin and removes the Pig Latin aspect of the word!

.SH OPTIONS
.IP "-h or -?"
Brings up a help message for how to use the program!

.SH AUTHORS
Zac Plett and Ezra Goss (Fall 2017)

.SH BUGS
None!
